#!/usr/bin/env bash
# Level 1 — Every expected config variable has a default in the entry point
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

EXPECTED_VARS=(
  CONTROL_PLANE_IP SSH_USER SSH_KEY_PATH K8S_VERSION CNI_PLUGIN POD_CIDR
  HELM_VERSION NFS_SERVER_IP NFS_PATH NFS_STORAGE_CLASS NFS_DEFAULT_SC
  NVIDIA_DRIVER_VERSION NVIDIA_OPEN_KERNEL NVIDIA_FABRIC_MANAGER NVIDIA_REBOOT_TIMEOUT
  GPU_TIMESLICING_ENABLED GPU_TIMESLICE_COUNT
  INSTALL_NVIDIA INSTALL_MONITORING INSTALL_NFS INSTALL_DASHBOARD INSTALL_VLLM
  INSTALL_CEPH INSTALL_MINIO INSTALL_INGRESS INSTALL_METALLB INSTALL_CERT_MANAGER
  INSTALL_HARDEN INSTALL_REGISTRY INSTALL_ARGOCD INSTALL_LOKI
  PROM_STACK_VERSION GRAFANA_ADMIN_PASSWORD GRAFANA_NODEPORT
  PROMETHEUS_NODEPORT ALERTMANAGER_NODEPORT PROM_RETENTION PROM_STORAGE_SIZE
  VLLM_NAMESPACE VLLM_NODEPORT VLLM_MODEL VLLM_DTYPE VLLM_GPU_COUNT VLLM_QUANTIZATION
  BACKUP_DIR BACKUP_KEEP
  CEPH_REPLICA_COUNT NS_CEPH CEPH_USE_ALL_NODES CEPH_USE_ALL_DEVICES
  METALLB_IP_RANGE CERT_MANAGER_ISSUER ARGOCD_NODEPORT LOKI_STORAGE_SIZE
  DASHBOARD_NODEPORT NS_MONITORING NS_GPU_OPERATOR NS_NFS
)

FAIL=0
for var in "${EXPECTED_VARS[@]}"; do
  if grep -F "${var}=" "${ROOT}/k8s_cluster_setup.sh" "${ROOT}/lib/config.sh" 2>/dev/null | grep -qF "{${var}:-"; then
    echo "  PASS  ${var}"
  else
    echo "  FAIL  ${var} — no default in entry point"
    FAIL=$(( FAIL + 1 ))
  fi
done


(( FAIL == 0 )) || { echo "FAIL: ${FAIL} variable(s) missing defaults"; exit 1; }
