#!/usr/bin/env bash
# =============================================================================
# wizard/sections/config.sh
# Part of the k8s-install wizard.
# Sourced by k8s_configure.sh — do not run directly.
# =============================================================================
# shellcheck shell=bash
# shellcheck source=../../k8s_configure.sh

write_config() {
  local safe_pw
  safe_pw=$(printf '%q' "$GRAFANA_ADMIN_PASSWORD")

  cat > "$CONFIG_FILE" <<CONFEOF
# =============================================================================
# k8s_cluster.conf — Generated by k8s_configure.sh on $(date)
# CONF_VERSION=${CONF_VERSION}
# =============================================================================

# ── SSH ───────────────────────────────────────────────────────────────────────
SSH_USER="${SSH_USER:-}"
SSH_KEY_PATH="${SSH_KEY_PATH:-}"

# ── Nodes ─────────────────────────────────────────────────────────────────────
CONTROL_PLANE_IP="${CONTROL_PLANE_IP:-}"
WORKER_IPS=${WORKER_IPS_STR:-}

# ── Kubernetes ────────────────────────────────────────────────────────────────
K8S_VERSION="${K8S_VERSION:-}"
POD_CIDR="${POD_CIDR:-}"
CNI_PLUGIN="${CNI_PLUGIN:-}"
HELM_VERSION="${HELM_VERSION:-}"

# ── NVIDIA ────────────────────────────────────────────────────────────────────
INSTALL_NVIDIA="${INSTALL_NVIDIA:-}"
NVIDIA_DRIVER_VERSION="${NVIDIA_DRIVER_VERSION:-}"
NVIDIA_OPEN_KERNEL="${NVIDIA_OPEN_KERNEL:-}"
NVIDIA_FABRIC_MANAGER="${NVIDIA_FABRIC_MANAGER:-}"
NVIDIA_REBOOT_TIMEOUT="${NVIDIA_REBOOT_TIMEOUT:-}"
NVIDIA_TOOLKIT_VERSION="${NVIDIA_TOOLKIT_VERSION:-}"

# ── Monitoring ────────────────────────────────────────────────────────────────
INSTALL_MONITORING="${INSTALL_MONITORING:-}"
PROM_STACK_VERSION="${PROM_STACK_VERSION:-}"
NS_MONITORING="${NS_MONITORING:-}"
GRAFANA_ADMIN_PASSWORD=${safe_pw}
GRAFANA_NODEPORT="${GRAFANA_NODEPORT:-}"
PROMETHEUS_NODEPORT="${PROMETHEUS_NODEPORT:-}"
ALERTMANAGER_NODEPORT="${ALERTMANAGER_NODEPORT:-}"
PROM_RETENTION="${PROM_RETENTION:-}"
PROM_STORAGE_SIZE="${PROM_STORAGE_SIZE:-}"

# ── NFS ───────────────────────────────────────────────────────────────────────
INSTALL_NFS="${INSTALL_NFS:-}"
NFS_SERVER_IP="${NFS_SERVER_IP:-}"
NFS_PATH="${NFS_PATH:-}"
NS_NFS="${NS_NFS:-}"
NFS_STORAGE_CLASS="${NFS_STORAGE_CLASS:-}"
NFS_DEFAULT_SC="${NFS_DEFAULT_SC:-}"

# ── GPU Operator ──────────────────────────────────────────────────────────────
NS_GPU_OPERATOR="${NS_GPU_OPERATOR:-}"
GPU_TIMESLICING_ENABLED="${GPU_TIMESLICING_ENABLED:-}"
GPU_TIMESLICE_COUNT="${GPU_TIMESLICE_COUNT:-}"

# ── Kubernetes Dashboard ──────────────────────────────────────────────────────
INSTALL_DASHBOARD="${INSTALL_DASHBOARD:-}"
DASHBOARD_VERSION="${DASHBOARD_VERSION:-}"
DASHBOARD_NODEPORT="${DASHBOARD_NODEPORT:-}"
NS_DASHBOARD="${NS_DASHBOARD:-}"

# ── Backup ────────────────────────────────────────────────────────────────────
BACKUP_DIR="${BACKUP_DIR:-}"
BACKUP_S3_BUCKET="${BACKUP_S3_BUCKET:-}"
BACKUP_KEEP="${BACKUP_KEEP:-}"

# ── Rook-Ceph ─────────────────────────────────────────────────────────────────
INSTALL_CEPH="${INSTALL_CEPH:-}"
NS_CEPH="${NS_CEPH:-}"
CEPH_REPLICA_COUNT="${CEPH_REPLICA_COUNT:-}"
CEPH_USE_ALL_NODES="${CEPH_USE_ALL_NODES:-}"
CEPH_USE_ALL_DEVICES="${CEPH_USE_ALL_DEVICES:-}"
CEPH_DEVICE_FILTER="${CEPH_DEVICE_FILTER:-}"
CEPH_DASHBOARD_NODEPORT="${CEPH_DASHBOARD_NODEPORT:-}"
CEPH_DEFAULT_SC="${CEPH_DEFAULT_SC:-}"

# ── MinIO ─────────────────────────────────────────────────────────────────────
INSTALL_MINIO="${INSTALL_MINIO:-}"
NS_MINIO="${NS_MINIO:-}"
MINIO_ROOT_USER="${MINIO_ROOT_USER:-}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-}"
MINIO_STORAGE_SIZE="${MINIO_STORAGE_SIZE:-}"
MINIO_NODEPORT_API="${MINIO_NODEPORT_API:-}"
MINIO_NODEPORT_CONSOLE="${MINIO_NODEPORT_CONSOLE:-}"

# ── ingress-nginx ─────────────────────────────────────────────────────────────
INSTALL_INGRESS="${INSTALL_INGRESS:-}"
NS_INGRESS="${NS_INGRESS:-}"
INGRESS_NODEPORT_HTTP="${INGRESS_NODEPORT_HTTP:-}"
INGRESS_NODEPORT_HTTPS="${INGRESS_NODEPORT_HTTPS:-}"

# ── MetalLB ───────────────────────────────────────────────────────────────────
INSTALL_METALLB="${INSTALL_METALLB:-}"
NS_METALLB="${NS_METALLB:-}"
METALLB_IP_RANGE="${METALLB_IP_RANGE:-}"

# ── cert-manager ──────────────────────────────────────────────────────────────
INSTALL_CERT_MANAGER="${INSTALL_CERT_MANAGER:-}"
NS_CERT_MANAGER="${NS_CERT_MANAGER:-}"
CERT_MANAGER_EMAIL="${CERT_MANAGER_EMAIL:-}"
CERT_MANAGER_ISSUER="${CERT_MANAGER_ISSUER:-}"

# ── Hardening ─────────────────────────────────────────────────────────────────
INSTALL_HARDEN="${INSTALL_HARDEN:-}"
HARDEN_RUN_KUBEBENCH="${HARDEN_RUN_KUBEBENCH:-}"

# ── Private Registry ──────────────────────────────────────────────────────────
INSTALL_REGISTRY="${INSTALL_REGISTRY:-}"
NS_REGISTRY="${NS_REGISTRY:-}"
REGISTRY_NODEPORT="${REGISTRY_NODEPORT:-}"
REGISTRY_STORAGE_SIZE="${REGISTRY_STORAGE_SIZE:-}"
REGISTRY_AUTH="${REGISTRY_AUTH:-}"
REGISTRY_USER="${REGISTRY_USER:-}"
REGISTRY_PASSWORD="${REGISTRY_PASSWORD:-}"

# ── ArgoCD ────────────────────────────────────────────────────────────────────
INSTALL_ARGOCD="${INSTALL_ARGOCD:-}"
NS_ARGOCD="${NS_ARGOCD:-}"
ARGOCD_NODEPORT="${ARGOCD_NODEPORT:-}"

# ── Loki ──────────────────────────────────────────────────────────────────────
INSTALL_LOKI="${INSTALL_LOKI:-}"
NS_LOKI="${NS_LOKI:-}"
LOKI_STORAGE_SIZE="${LOKI_STORAGE_SIZE:-}"
LOKI_NODEPORT="${LOKI_NODEPORT:-}"

# ── KubeRay ───────────────────────────────────────────────────────────────────
INSTALL_RAY="${INSTALL_RAY:-}"
NS_RAY="${NS_RAY:-}"
RAY_VERSION="${RAY_VERSION:-}"
RAY_OPERATOR_VERSION="${RAY_OPERATOR_VERSION:-}"
RAY_HEAD_CPU="${RAY_HEAD_CPU:-}"
RAY_HEAD_MEM="${RAY_HEAD_MEM:-}"
RAY_WORKER_REPLICAS="${RAY_WORKER_REPLICAS:-}"
RAY_WORKER_CPU="${RAY_WORKER_CPU:-}"
RAY_WORKER_MEM="${RAY_WORKER_MEM:-}"
RAY_WORKER_GPU="${RAY_WORKER_GPU:-}"
RAY_DASHBOARD_NODEPORT="${RAY_DASHBOARD_NODEPORT:-}"
RAY_ENABLE_AUTOSCALING="${RAY_ENABLE_AUTOSCALING:-}"
RAY_MIN_WORKERS="${RAY_MIN_WORKERS:-}"
RAY_MAX_WORKERS="${RAY_MAX_WORKERS:-}"

# ── vLLM quantization ─────────────────────────────────────────────────────────
VLLM_QUANTIZATION="${VLLM_QUANTIZATION:-}"

# ── vLLM Production Stack ────────────────────────────────────────────────────
INSTALL_VLLM="${INSTALL_VLLM:-}"
VLLM_NAMESPACE="${VLLM_NAMESPACE:-}"
VLLM_NODEPORT="${VLLM_NODEPORT:-}"
# Legacy single-model vars (backward compat — VLLM_MODELS array takes precedence)
VLLM_MODEL="${VLLM_MODEL:-}"
VLLM_DTYPE="${VLLM_DTYPE:-}"
VLLM_MAX_MODEL_LEN="${VLLM_MAX_MODEL_LEN:-}"
VLLM_GPU_COUNT="${VLLM_GPU_COUNT:-}"
VLLM_CPU_REQUEST="${VLLM_CPU_REQUEST:-}"
VLLM_CPU_LIMIT="${VLLM_CPU_LIMIT:-}"
VLLM_MEM_REQUEST="${VLLM_MEM_REQUEST:-}"
VLLM_MEM_LIMIT="${VLLM_MEM_LIMIT:-}"
VLLM_EXTRA_ARGS="${VLLM_EXTRA_ARGS:-}"
VLLM_STORAGE_SIZE="${VLLM_STORAGE_SIZE:-}"
VLLM_REUSE_PVC="${VLLM_REUSE_PVC:-}"
VLLM_PVC_NAME="${VLLM_PVC_NAME:-}"
VLLM_QUANTIZATION="${VLLM_QUANTIZATION:-}"
VLLM_NODE_SELECTOR="${VLLM_NODE_SELECTOR:-}"
VLLM_USE_RAY="${VLLM_USE_RAY:-}"
CONFEOF

  # Append VLLM_MODELS array (bash arrays cannot go inside a heredoc)
  {
    echo ""
    echo "# Multi-model array (one pipe-delimited spec per model)"
    echo "VLLM_MODELS=("; \
    for _ms in "${VLLM_MODELS[@]:-}"; do
      [[ -n "$_ms" ]] && printf '  %q\n' "$_ms"
    done; \
    echo ")"
  } >> "$CONFIG_FILE"

  chmod 600 "$CONFIG_FILE"
  ok "Configuration saved to ${CONFIG_FILE}"
}

patch_installer() {
  if [[ ! -f "$INSTALLER" ]]; then
    warn_msg "Installer not found at ${INSTALLER} — config written but installer not patched."
    return
  fi
  local worker_arr_str="$WORKER_IPS_STR"
  local tmp; tmp=$(mktemp)

  awk -v cp="${CONTROL_PLANE_IP:-}" \
      -v wu="${SSH_USER:-}" \
      -v wk="${SSH_KEY_PATH:-}" \
      -v kv="${K8S_VERSION:-}" \
      -v pc="${POD_CIDR:-}" \
      -v cni="${CNI_PLUGIN:-}" \
      -v nfs_ip="${NFS_SERVER_IP:-}" \
      -v nfs_path="${NFS_PATH:-}" \
      -v nv="${NVIDIA_DRIVER_VERSION:-}" \
      -v nv_open="${NVIDIA_OPEN_KERNEL:-}" \
      -v nv_fm="${NVIDIA_FABRIC_MANAGER:-}" \
      -v nv_rt="${NVIDIA_REBOOT_TIMEOUT:-}" \
      -v nv_tkver="${NVIDIA_TOOLKIT_VERSION:-}" \
      -v vllm_nodesel="${VLLM_NODE_SELECTOR:-}" \
      -v vllm_useray="${VLLM_USE_RAY:-}" \
      -v hv="${HELM_VERSION:-}" \
      -v ns_mon="${NS_MONITORING:-}" \
      -v ns_gpu="${NS_GPU_OPERATOR:-}" \
      -v ns_nfs="${NS_NFS:-}" \
      -v prom_ver="${PROM_STACK_VERSION:-}" \
      -v gpass="${GRAFANA_ADMIN_PASSWORD:-}" \
      -v inst_dash="${INSTALL_DASHBOARD:-}" \
      -v dash_ver="${DASHBOARD_VERSION:-}" \
      -v dash_port="${DASHBOARD_NODEPORT:-}" \
      -v ns_dash="${NS_DASHBOARD:-}" \
      -v inst_vllm="${INSTALL_VLLM:-}" \
      -v vllm_ns="${VLLM_NAMESPACE:-}" \
      -v vllm_port="${VLLM_NODEPORT:-}" \
      -v vllm_model="${VLLM_MODEL:-}" \
      -v vllm_hft="${VLLM_HF_TOKEN:-}" \
      -v vllm_dtype="${VLLM_DTYPE:-}" \
      -v vllm_maxlen="${VLLM_MAX_MODEL_LEN:-}" \
      -v vllm_gpus="${VLLM_GPU_COUNT:-}" \
      -v vllm_cpureq="${VLLM_CPU_REQUEST:-}" \
      -v vllm_cpulim="${VLLM_CPU_LIMIT:-}" \
      -v vllm_memreq="${VLLM_MEM_REQUEST:-}" \
      -v vllm_memlim="${VLLM_MEM_LIMIT:-}" \
      -v vllm_extra="${VLLM_EXTRA_ARGS:-}" \
      -v vllm_stosize="${VLLM_STORAGE_SIZE:-}" \
      -v vllm_reuse="${VLLM_REUSE_PVC:-}" \
      -v vllm_pvc="${VLLM_PVC_NAME:-}" \
      -v gts_en="${GPU_TIMESLICING_ENABLED:-}" \
      -v gts_cnt="${GPU_TIMESLICE_COUNT:-}" \
      -v inst_ceph="${INSTALL_CEPH:-}" \
      -v ceph_rep="${CEPH_REPLICA_COUNT:-}" \
      -v ceph_nodes="${CEPH_USE_ALL_NODES:-}" \
      -v ceph_devs="${CEPH_USE_ALL_DEVICES:-}" \
      -v ceph_filt="${CEPH_DEVICE_FILTER:-}" \
      -v ceph_port="${CEPH_DASHBOARD_NODEPORT:-}" \
      -v ceph_def="${CEPH_DEFAULT_SC:-}" \
      -v inst_minio="${INSTALL_MINIO:-}" \
      -v minio_user="${MINIO_ROOT_USER:-}" \
      -v minio_pass="${MINIO_ROOT_PASSWORD:-}" \
      -v minio_size="${MINIO_STORAGE_SIZE:-}" \
      -v minio_api="${MINIO_NODEPORT_API:-}" \
      -v minio_con="${MINIO_NODEPORT_CONSOLE:-}" \
      -v inst_ingress="${INSTALL_INGRESS:-}" \
      -v ing_http="${INGRESS_NODEPORT_HTTP:-}" \
      -v ing_https="${INGRESS_NODEPORT_HTTPS:-}" \
      -v inst_metallb="${INSTALL_METALLB:-}" \
      -v mlb_range="${METALLB_IP_RANGE:-}" \
      -v inst_cm="${INSTALL_CERT_MANAGER:-}" \
      -v cm_email="${CERT_MANAGER_EMAIL:-}" \
      -v cm_issuer="${CERT_MANAGER_ISSUER:-}" \
      -v inst_harden="${INSTALL_HARDEN:-}" \
      -v inst_reg="${INSTALL_REGISTRY:-}" \
      -v reg_port="${REGISTRY_NODEPORT:-}" \
      -v reg_size="${REGISTRY_STORAGE_SIZE:-}" \
      -v reg_auth="${REGISTRY_AUTH:-}" \
      -v reg_user="${REGISTRY_USER:-}" \
      -v reg_pass="${REGISTRY_PASSWORD:-}" \
      -v inst_argo="${INSTALL_ARGOCD:-}" \
      -v argo_port="${ARGOCD_NODEPORT:-}" \
      -v inst_loki="${INSTALL_LOKI:-}" \
      -v loki_size="${LOKI_STORAGE_SIZE:-}" \
      -v ray_inst="${INSTALL_RAY:-}" \
      -v ray_ns="${NS_RAY:-}" \
      -v ray_ver="${RAY_VERSION:-}" \
      -v ray_opver="${RAY_OPERATOR_VERSION:-}" \
      -v ray_hcpu="${RAY_HEAD_CPU:-}" \
      -v ray_hmem="${RAY_HEAD_MEM:-}" \
      -v ray_wreps="${RAY_WORKER_REPLICAS:-}" \
      -v ray_wcpu="${RAY_WORKER_CPU:-}" \
      -v ray_wmem="${RAY_WORKER_MEM:-}" \
      -v ray_wgpu="${RAY_WORKER_GPU:-}" \
      -v ray_port="${RAY_DASHBOARD_NODEPORT:-}" \
      -v ray_auto="${RAY_ENABLE_AUTOSCALING:-}" \
      -v ray_min="${RAY_MIN_WORKERS:-}" \
      -v ray_max="${RAY_MAX_WORKERS:-}" \
      -v vllm_quant="${VLLM_QUANTIZATION:-}" \
      -v bkp_dir="${BACKUP_DIR:-}" \
      -v bkp_s3="${BACKUP_S3_BUCKET:-}" \
      -v bkp_keep="${BACKUP_KEEP:-}" \
      -v workers="$worker_arr_str" \
  'BEGIN { in_conf=0 }
   /^# CONFIGURATION — Edit these values/ { in_conf=1 }
   in_conf && /^CONTROL_PLANE_IP=/  { print "CONTROL_PLANE_IP=\"" cp "\""; next }
   in_conf && /^WORKER_IPS=/        { print "WORKER_IPS=" workers;         next }
   in_conf && /^SSH_USER=/          { print "SSH_USER=\"" wu "\"";          next }
   in_conf && /^SSH_KEY_PATH=/      { print "SSH_KEY_PATH=\"" wk "\"";      next }
   in_conf && /^K8S_VERSION=/       { print "K8S_VERSION=\"" kv "\"";       next }
   in_conf && /^POD_CIDR=/          { print "POD_CIDR=\"" pc "\"";          next }
   in_conf && /^CNI_PLUGIN=/        { print "CNI_PLUGIN=\"" cni "\"";       next }
   in_conf && /^NFS_SERVER_IP=/     { print "NFS_SERVER_IP=\"" nfs_ip "\""; next }
   in_conf && /^NFS_PATH=/          { print "NFS_PATH=\"" nfs_path "\"";    next }
   in_conf && /^NVIDIA_DRIVER_VERSION=/ { print "NVIDIA_DRIVER_VERSION=\"" nv "\""; next }
   in_conf && /^NVIDIA_OPEN_KERNEL=/    { print "NVIDIA_OPEN_KERNEL=\"" nv_open "\""; next }
   in_conf && /^NVIDIA_FABRIC_MANAGER=/ { print "NVIDIA_FABRIC_MANAGER=\"" nv_fm "\""; next }
   in_conf && /^NVIDIA_REBOOT_TIMEOUT=/ { print "NVIDIA_REBOOT_TIMEOUT=\"" nv_rt "\""; next }
   in_conf && /^NVIDIA_TOOLKIT_VERSION=/ { print "NVIDIA_TOOLKIT_VERSION=\"" nv_tkver "\""; next }
   in_conf && /^HELM_VERSION=/      { print "HELM_VERSION=\"" hv "\"";      next }
   in_conf && /^NS_MONITORING=/     { print "NS_MONITORING=\"" ns_mon "\""; next }
   in_conf && /^NS_GPU_OPERATOR=/   { print "NS_GPU_OPERATOR=\"" ns_gpu "\""; next }
   in_conf && /^NS_NFS=/            { print "NS_NFS=\"" ns_nfs "\"";        next }
   in_conf && /^PROM_STACK_VERSION=/ { print "PROM_STACK_VERSION=\"" prom_ver "\""; next }
   in_conf && /^GRAFANA_ADMIN_PASSWORD=/ { print "GRAFANA_ADMIN_PASSWORD=\"" gpass "\""; next }
   in_conf && /^INSTALL_DASHBOARD=/ { print "INSTALL_DASHBOARD=\"" inst_dash "\""; next }
   in_conf && /^DASHBOARD_VERSION=/ { print "DASHBOARD_VERSION=\"" dash_ver "\""; next }
   in_conf && /^DASHBOARD_NODEPORT=/ { print "DASHBOARD_NODEPORT=\"" dash_port "\""; next }
   in_conf && /^NS_DASHBOARD=/      { print "NS_DASHBOARD=\"" ns_dash "\""; next }
   in_conf && /^INSTALL_VLLM=/      { print "INSTALL_VLLM=\"" inst_vllm "\""; next }
   in_conf && /^VLLM_NAMESPACE=/    { print "VLLM_NAMESPACE=\"" vllm_ns "\""; next }
   in_conf && /^VLLM_NODEPORT=/     { print "VLLM_NODEPORT=\"" vllm_port "\""; next }
   in_conf && /^VLLM_MODEL=/        { print "VLLM_MODEL=\"" vllm_model "\""; next }
   in_conf && /^VLLM_HF_TOKEN=/     { print "VLLM_HF_TOKEN=\"" vllm_hft "\""; next }
   in_conf && /^VLLM_DTYPE=/        { print "VLLM_DTYPE=\"" vllm_dtype "\""; next }
   in_conf && /^VLLM_MAX_MODEL_LEN=/ { print "VLLM_MAX_MODEL_LEN=\"" vllm_maxlen "\""; next }
   in_conf && /^VLLM_GPU_COUNT=/    { print "VLLM_GPU_COUNT=\"" vllm_gpus "\""; next }
   in_conf && /^VLLM_CPU_REQUEST=/  { print "VLLM_CPU_REQUEST=\"" vllm_cpureq "\""; next }
   in_conf && /^VLLM_CPU_LIMIT=/    { print "VLLM_CPU_LIMIT=\"" vllm_cpulim "\""; next }
   in_conf && /^VLLM_MEM_REQUEST=/  { print "VLLM_MEM_REQUEST=\"" vllm_memreq "\""; next }
   in_conf && /^VLLM_MEM_LIMIT=/    { print "VLLM_MEM_LIMIT=\"" vllm_memlim "\""; next }
   in_conf && /^VLLM_EXTRA_ARGS=/   { print "VLLM_EXTRA_ARGS=\"" vllm_extra "\""; next }
   in_conf && /^VLLM_STORAGE_SIZE=/ { print "VLLM_STORAGE_SIZE=\"" vllm_stosize "\""; next }
   in_conf && /^VLLM_REUSE_PVC=/    { print "VLLM_REUSE_PVC=\"" vllm_reuse "\""; next }
   in_conf && /^VLLM_PVC_NAME=/     { print "VLLM_PVC_NAME=\"" vllm_pvc "\""; next }
   in_conf && /^GPU_TIMESLICING_ENABLED=/ { print "GPU_TIMESLICING_ENABLED=\"" gts_en "\""; next }
   in_conf && /^GPU_TIMESLICE_COUNT=/     { print "GPU_TIMESLICE_COUNT=\"" gts_cnt "\""; next }
   in_conf && /^INSTALL_CEPH=/             { print "INSTALL_CEPH=\"" inst_ceph "\""; next }
   in_conf && /^CEPH_REPLICA_COUNT=/       { print "CEPH_REPLICA_COUNT=\"" ceph_rep "\""; next }
   in_conf && /^CEPH_USE_ALL_NODES=/       { print "CEPH_USE_ALL_NODES=\"" ceph_nodes "\""; next }
   in_conf && /^CEPH_USE_ALL_DEVICES=/     { print "CEPH_USE_ALL_DEVICES=\"" ceph_devs "\""; next }
   in_conf && /^CEPH_DEVICE_FILTER=/       { print "CEPH_DEVICE_FILTER=\"" ceph_filt "\""; next }
   in_conf && /^CEPH_DASHBOARD_NODEPORT=/  { print "CEPH_DASHBOARD_NODEPORT=\"" ceph_port "\""; next }
   in_conf && /^CEPH_DEFAULT_SC=/          { print "CEPH_DEFAULT_SC=\"" ceph_def "\""; next }
   in_conf && /^INSTALL_MINIO=/            { print "INSTALL_MINIO=\"" inst_minio "\""; next }
   in_conf && /^MINIO_ROOT_USER=/          { print "MINIO_ROOT_USER=\"" minio_user "\""; next }
   in_conf && /^MINIO_ROOT_PASSWORD=/      { print "MINIO_ROOT_PASSWORD=\"" minio_pass "\""; next }
   in_conf && /^MINIO_STORAGE_SIZE=/       { print "MINIO_STORAGE_SIZE=\"" minio_size "\""; next }
   in_conf && /^MINIO_NODEPORT_API=/       { print "MINIO_NODEPORT_API=\"" minio_api "\""; next }
   in_conf && /^MINIO_NODEPORT_CONSOLE=/   { print "MINIO_NODEPORT_CONSOLE=\"" minio_con "\""; next }
   in_conf && /^INSTALL_INGRESS=/          { print "INSTALL_INGRESS=\"" inst_ingress "\""; next }
   in_conf && /^INGRESS_NODEPORT_HTTP=/    { print "INGRESS_NODEPORT_HTTP=\"" ing_http "\""; next }
   in_conf && /^INGRESS_NODEPORT_HTTPS=/   { print "INGRESS_NODEPORT_HTTPS=\"" ing_https "\""; next }
   in_conf && /^INSTALL_METALLB=/          { print "INSTALL_METALLB=\"" inst_metallb "\""; next }
   in_conf && /^METALLB_IP_RANGE=/         { print "METALLB_IP_RANGE=\"" mlb_range "\""; next }
   in_conf && /^INSTALL_CERT_MANAGER=/     { print "INSTALL_CERT_MANAGER=\"" inst_cm "\""; next }
   in_conf && /^CERT_MANAGER_EMAIL=/       { print "CERT_MANAGER_EMAIL=\"" cm_email "\""; next }
   in_conf && /^CERT_MANAGER_ISSUER=/      { print "CERT_MANAGER_ISSUER=\"" cm_issuer "\""; next }
   in_conf && /^INSTALL_HARDEN=/           { print "INSTALL_HARDEN=\"" inst_harden "\""; next }
   in_conf && /^INSTALL_REGISTRY=/         { print "INSTALL_REGISTRY=\"" inst_reg "\""; next }
   in_conf && /^REGISTRY_NODEPORT=/        { print "REGISTRY_NODEPORT=\"" reg_port "\""; next }
   in_conf && /^REGISTRY_STORAGE_SIZE=/    { print "REGISTRY_STORAGE_SIZE=\"" reg_size "\""; next }
   in_conf && /^REGISTRY_AUTH=/            { print "REGISTRY_AUTH=\"" reg_auth "\""; next }
   in_conf && /^REGISTRY_USER=/            { print "REGISTRY_USER=\"" reg_user "\""; next }
   in_conf && /^REGISTRY_PASSWORD=/        { print "REGISTRY_PASSWORD=\"" reg_pass "\""; next }
   in_conf && /^INSTALL_ARGOCD=/           { print "INSTALL_ARGOCD=\"" inst_argo "\""; next }
   in_conf && /^ARGOCD_NODEPORT=/          { print "ARGOCD_NODEPORT=\"" argo_port "\""; next }
   in_conf && /^INSTALL_LOKI=/             { print "INSTALL_LOKI=\"" inst_loki "\""; next }
   in_conf && /^LOKI_STORAGE_SIZE=/        { print "LOKI_STORAGE_SIZE=\"" loki_size "\""; next }
   in_conf && /^INSTALL_RAY=/            { print "INSTALL_RAY=\"" ray_inst  "\"" ; next }
   in_conf && /^NS_RAY=/                 { print "NS_RAY=\"" ray_ns "\"" ; next }
   in_conf && /^RAY_VERSION=/            { print "RAY_VERSION=\"" ray_ver  "\"" ; next }
   in_conf && /^RAY_OPERATOR_VERSION=/   { print "RAY_OPERATOR_VERSION=\"" ray_opver "\"" ; next }
   in_conf && /^RAY_HEAD_CPU=/           { print "RAY_HEAD_CPU=\"" ray_hcpu "\"" ; next }
   in_conf && /^RAY_HEAD_MEM=/           { print "RAY_HEAD_MEM=\"" ray_hmem "\"" ; next }
   in_conf && /^RAY_WORKER_REPLICAS=/    { print "RAY_WORKER_REPLICAS=\"" ray_wreps "\"" ; next }
   in_conf && /^RAY_WORKER_CPU=/         { print "RAY_WORKER_CPU=\"" ray_wcpu "\"" ; next }
   in_conf && /^RAY_WORKER_MEM=/         { print "RAY_WORKER_MEM=\"" ray_wmem "\"" ; next }
   in_conf && /^RAY_WORKER_GPU=/         { print "RAY_WORKER_GPU=\"" ray_wgpu "\"" ; next }
   in_conf && /^RAY_DASHBOARD_NODEPORT=/ { print "RAY_DASHBOARD_NODEPORT=\"" ray_port "\"" ; next }
   in_conf && /^RAY_ENABLE_AUTOSCALING=/ { print "RAY_ENABLE_AUTOSCALING=\"" ray_auto "\"" ; next }
   in_conf && /^RAY_MIN_WORKERS=/        { print "RAY_MIN_WORKERS=\"" ray_min "\"" ; next }
   in_conf && /^RAY_MAX_WORKERS=/        { print "RAY_MAX_WORKERS=\"" ray_max "\"" ; next }
   in_conf && /^VLLM_QUANTIZATION=/        { print "VLLM_QUANTIZATION=\"" vllm_quant "\""; next }
   in_conf && /^VLLM_NODE_SELECTOR=/  { print "VLLM_NODE_SELECTOR=\"" vllm_nodesel "\"" ; next }
   in_conf && /^VLLM_USE_RAY=/        { print "VLLM_USE_RAY=\"" vllm_useray "\"" ; next }
   in_conf && /^BACKUP_DIR=/               { print "BACKUP_DIR=\"" bkp_dir "\""; next }
   in_conf && /^BACKUP_S3_BUCKET=/         { print "BACKUP_S3_BUCKET=\"" bkp_s3 "\""; next }
   in_conf && /^BACKUP_KEEP=/              { print "BACKUP_KEEP=\"" bkp_keep "\""; next }
   /^# ─.*SANITY CHECKS/ { in_conf=0 }
   { print }' "$INSTALLER" > "$tmp"

  chmod 700 "$tmp"
  mv "$tmp" "$INSTALLER"
  ok "Installer patched with your configuration."
}

